---
Name: SettingsContent-ms
Description: A SettingsContent-ms file was introduced in Windows 10 and allows a user to create “shortcuts” to various Windows 10 setting pages.
Author: 'Hegusung'
Created: 2024-10-20
Categories:
  - Category: CMD
    Description: Command execution
    Usecase: Execute a command
    MitreID: T1220
    OperatingSystem: Windows 10, Windows 11
    Code_Sample:
    Tags:
      - Origin: Clickable
Detection:
Resources:
  - Link: https://posts.specterops.io/the-tale-of-settingcontent-ms-files-f1ea253e4d39
  - Link: https://hegusung.github.io/LOLBAS-Project-hegusung.github.io/#/cmd
Acknowledgement:
  - Person: Matt Nelson
    Handle: '@enigma0x3'
